version: 2.1

orbs:
  python: circleci/python@0.2.1



jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python --version

workflows:
  main:
    jobs:
      - build-and-test
