jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python --version
      - python/load-cache
      - python/install-deps
      - python/save-cache
