version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run: |
          pip3 -q install -r requirements.txt
          conda install -c quantopian ta-lib
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test