    name: GitHub Pages Deploy Action
    on:
        # Branch name(s) which have the source file for site/documentation
        push: [ <write-branch-here> ]
    jobs:
        deploy-pages:
            name: Deploy to GitHub Pages
            runs-on: ubuntu-latest
            steps:
                - uses: avinal/github-pages-deploy-action@main
                  with:
                    # GitHub access token with Repo Access
                    GITHUB_TOKEN: ${{ github.token }}
                    # For python write python package and additional packages if any - "python3 python3-pip"
                    LANGUAGE: "python3"
                    # Write make command to generate html e.g.- "make html"
                    MAKE_COMMAND: |
                      echo 'test'
                      npm i docsify-cli -g
                      docsify init docs
                      docsify serve docs
                    # Write the branch name for storing github pages source
                    PAGES_BRANCH: "gh-pages"
                    # Write the branch name having source files for site/documentation
                    BUILD_FROM: "master"
                    # Write the name of the output folder where generated html is stored by makefile.
                    DOCS_FOLDER: "docs"