name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: loading dependencies
        run: |
          pip install --upgrade pip
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          sudo apt upgrade
          pip install ta-lib
          cd ..
          pip3 install -r requirements.txt

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/github-pages-deploy-action@main
        with:
          # GitHub access token with Repo Access
          GITHUB_TOKEN: ${{ github.token }}
          # For python write python package and additional packages if any - "python3 python3-pip"
          LANGUAGE: "python3"
          # Write make command to generate html e.g.- "make html"
          MAKE_COMMAND: |
            make html
          # Write the branch name for storing github pages source
          PAGES_BRANCH: "gh-pages"
          # Write the branch name having source files for site/documentation
          BUILD_FROM: "master"
          # Write the name of the output folder where generated html is stored by makefile.
          DOCS_FOLDER: "docs"